version: "3.9"
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/planifitai
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: celery -A app.core.celery_utils.create_celery worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/planifitai
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: planifitai
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"