services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - AI_SERVICE_URL=http://ai:8080
      - AI_INTERNAL_SECRET=${AI_INTERNAL_SECRET}
    depends_on:
      - db
      - redis
      - ai
    ports:
      - "8000:8000"
    networks:
      - internal
  worker:
    build: .
    command: celery -A app.core.celery_utils.celery_app worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AI_SERVICE_URL=http://ai:8080
      - AI_INTERNAL_SECRET=${AI_INTERNAL_SECRET}
    depends_on:
      - db
      - redis
      - ai
    networks:
      - internal
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: planifitai
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  ai:
    build: ./services/ai
    environment:
      - AI_INTERNAL_SECRET=${AI_INTERNAL_SECRET}
    networks:
      - internal

networks:
  internal:
    driver: bridge
