"""create_user_profiles_table

Revision ID: 796df29988e1
Revises: c5379909c095
Create Date: 2025-08-12 12:17:11.115228

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "796df29988e1"
down_revision: Union[str, Sequence[str], None] = "c5379909c095"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column(
            "activity_level",
            sa.Enum(
                "SEDENTARY",
                "LIGHTLY_ACTIVE",
                "MODERATELY_ACTIVE",
                "VERY_ACTIVE",
                "EXTRA_ACTIVE",
                name="activitylevel",
            ),
            nullable=True,
        ),
        sa.Column(
            "goal",
            sa.Enum("LOSE_WEIGHT", "MAINTAIN_WEIGHT", "GAIN_WEIGHT", name="goal"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_profiles_full_name"), "user_profiles", ["full_name"], unique=False
    )
    op.create_index(op.f("ix_user_profiles_id"), "user_profiles", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_profiles_user_id"), "user_profiles", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_profiles_user_id"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_id"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_full_name"), table_name="user_profiles")
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
