"""Create routines, routine_days, exercise_catalog, and routine_exercises tables

Revision ID: 7f4dbf4a3e20
Revises: b234998e2f1b
Create Date: 2025-08-13 11:37:41.686420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f4dbf4a3e20"
down_revision: Union[str, Sequence[str], None] = "b234998e2f1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
