"""create users table

Revision ID: aac2998e7984
Revises:
Create Date: 2025-08-07 16:13:41.893129

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "aac2998e7984"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
