name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pip install pip-audit safety
      - name: pip-audit
        run: pip-audit -r requirements.txt --strict
      - name: safety
        run: safety check -r requirements.txt || true
      - name: pytest
        run: pytest -q
