name: Auto Format (Black)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run Black
        run: black .
      - name: Create Pull Request if changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(format): apply Black formatting"
          title: "chore(format): apply Black formatting"
          body: "This PR applies Black formatting automatically."
          branch: ci/auto-format
          delete-branch: true
