name: Auto Format (Black & Ruff)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Black & Ruff
        run: |
          python -m pip install --upgrade pip
          pip install black ruff
      - name: Run formatters
        run: black . && ruff check . --fix
      - name: Debug formatting diff
        run: |
          git status --short
          git diff --unified=0
      - name: Create Pull Request if changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(format): apply Black & Ruff auto-fixes"
          branch: ci/auto-format
          title: "chore(format): auto-format code (Black/Ruff)"
          body: "Este PR aplica formato automático. Si no ves PR, probablemente no había cambios de estilo pendientes."
          labels: ci
